module.exports = [
  "do u realise he just came back today for fun but have been playing a bit offline on wl? Didn't spent a single cent on this yolo heist btw, keep hating for nothing bronze bot ",
  "Why when X gets mald he gets banned, while cops powergame and get mald whenever they fail and devs dont do nothing about it. X literally had the world in his hands, and they take it away while those other are really breaking rules of the server. Disappointing to be honest.",
  "Honestly if it wasn’t for XQC I wouldn’t even be watching GTA roleplay. He’s done more for the server and the game then anyone else with his following and has boosted the careers of so many people just by playing the game.",
  "NoPixel is literally ran by cops and they all have power trips. NoPixel is just like the Stanford Prison Experimental... truly sad to see...",
  "Xqc gets permaed right before his court case with Wrangler, a court case Wrangler was almost guaranteed to lose. That’s a little sus to me.",
  'i love how admins "cops" can’t see or find anything wrong with thier actions and blame/ban everyone else for actions caused by them in the f,irst place',
  "NoPixel is a police state and the fact that the admin and cops are a single entity should be scary enough",
  "the weirdest thing for me watching gta rp is how mad some of these cops get for people being criminals and, comiting crime in a rp gta game..",
  "He not too mad that he takes L but taking L because of shit that wrangler does it not fun to play.",
  "x isnt even like his character irl u see his irl streams and he’s very polite and nice to others an,d with his friends he’s good at portraying himself as the bad guy as his character its weird people think he’s like that",
  "Get ready to see some boring as RP from now on!",
  "Welp now that X is gone, Wrangler/mike block gon,na target the next biggest crim aka Yuno",
  "no one on the server wants him banned idk why he was. bans should be a majority vote on a, roleplay server not some random persons decision",
  "if it wasn’t for X, NoPixel would’ve been trash",
  "It feels weird to feel bad for a millionaire, bu,t I know that X really enjoyed Nopixel. I’m sad that he had that taken away from him for braking the rules a few times. I can’t be the only one that believes X brought a hell of a lot more into the server than he took away. This is a sad day for GTA RP, regardless of whether or not you like X. Nopixel just lost 140k viewers every day.",
  "Sometimes I felt so bad for him because there`s always a shitlord complaining, backseats, and hate watchers. he always gets shit when people told him his comunity is garbage because they harrased other streamer. But, have you ever think he gets the same treatment as well? Last night when he kill penta 5k penta`s viewers chat hopped and tell him to ki11 himself because he killed pent,a or when he scream at moon moon he gets chat hopped by moonmoon too. the point is, the double standard people wan",
  "andrews is alright and all but lets not pretend meeting the people behind the police rp is the solution. the solution is applying rules to every player equally especially people like penta, angel, and lenny who, cant stop power gaming when they cant get what they want in rp. specifically penta who cant taking a single fucking L and will cheat so hes always ahead of xqc. penta will always be W > RP",
  "Penta is not a real person to me lmao, and ofc he wants X to be a cop, then he wouldnt have to worry about getting banned",
  "everyone talkiong about X, but it’s clearly penta that is the problem. I hate to watch XQC, but it’s so obvious that penta, is the instagator",
  "the difference between cops and crims is that most crims also play cop characters but cops are literally cop mains and have no clue whats it ,like to be a crim in nopixel 3.0, these people don’t know anything about taking L’s and all the frustration behind losing that much money, getting tazed in cars, water, rammed, spam tackled and the hours of irl time ur spending behind bars while cops are all having a good time and on their worst day have to wait 15 mins to be revived.",
  "I feel like even if you ride with Cops and get to know them. It doesn’t change the Wrangler’s, the Lenny’s, the Angel’s, the Dan Failey’s. Like he already feels bad when he has to shoot the nice Cops to prove a point.",
  "the cops have too much power in no pixel and it really ruins the server at the moment.",
  "I dunno, since the early days of OW, xqc has always been a pain in the ass to play game,s with.There’s a reason he gets banned from practically everything.",
  "Now it feels like when ur playing in no pixel is, just stay away from the cops if u can and dont do crims or if u ever get caught by doin crims, just surre,nder and comply. Dont fight with cops. Like ever and move on.",
  "This is just sad. If it weren’t for Penta being friends with the admins, it would’ve been him banned instead of xQc",
  "The fact that he actually called an Officer in character is so sad. It got to a point where the targeting was so bad,, that he reached out to his mortal enemy for help.",
  "Its really sad seeing that xQc got banned, at the end of the day he just wants to make content for his viewers. The fact that hes pulling off stuff nobody else has ever, done before while being quite new to RP is impressive. Love him or hate him, theres no denying the fact he had a big impact on the server and will be a big part of NoPixel history xqcL",
  "XQC has changed so many people’s life, the streamers in NoPixel are grateful for him.",
  "his character is solo rider being an asshole to many people and sometimes ratting them, out lol. His character is always against cops doesn’t matter If it’s Tessa or Kyle lol. People don’t realize if insults in game it isn’t personal.",
  "From watch I watched the cops did him dirty. He brought evidence and two. Lawyers helped build a case on one and had a case on another .would have ruined multiple cops so what is the easiest thing to do ban X",
  "It wasn’t even his fault if Moonmoon and penta did those things to someone else it’ll literally make anybody mald and get personal cuz for the last few weeks xQc clips have been full of penta and I don’t even ,watch his streams but it’s like penta wants him to get banned it’s like personal to penta",
  "There is a reason XQC is the top streamer on twitch RN. He’s crazy, he makes mistakes, he malds but despite all those things, hes a really good dude. He’s always willing to help the smaller guys, teaching no-names to hack, and doing bank jobs with small streamers. He’s just ACTUALLY a normal good d,ude, who happens to be the biggest streamer on twitch. He may not be perfect, but neither is anyone else, he just has more eyes watching, but they are watching BECAUSE he is who he is.",
  "If I was X I wouldn’t even care. Just send penta and moon moon screen shots of bank accounts and laugh at them.",
  "That server needs a complete overhaul top to bottom. The pd needs to learn actual laws and follow them. Being a ,cop shouldn’t be about wins. Koil rarely plays anymore and without him on these idiots do whatever they want.",
  "People like penta can ruin an entire server. Moonmoon is no better. They both use Metta and stream snipe. Its proven live on their streams. Im done watching and supporting no pixel. I pulled all my subs and won’t watch aga,in till those looser are permabanned",
  "They r molding because the most famous streamer with the most powerful community dont want to rp with them . And they r jaluss to people who x is rping with them like benji ramee , randy, and santi .",
  "People always like to say that x’s chat is a bunch of weirdos, but I went into moon moons stream the other day and i’ve never seen a weirder chat in my 6 years of watching twitch",
  "Can somebody tell me how this guy isnt banned yet? X literally does small things and get banned for it while this dude metagames and powergames all the time and doesnt get banned., Atleast ban him for 3 days bruh",
  "moon moon is literally so bad at rp idk why they havent banned him,,,like ban him and replace his slot with x bruh ..oh wait cant do that cuz then penta will just whine like a little girl and power play him AGAIN,. and metahim AGAIN. and potentially take his phone AGAIN. or maybe take his vpn AGAIN. smh",
  "penta and moon moon arte the most cringey and kill rp cops LOL funny they went after X. I am not a x viewer but they went hard on him.",
  "If u can’t beat him ban him -Penta and Moon. 😂😂",
  "if you permaban is it ip ban?",
  "40 yr old guy got lucky OMEGAL,AUGHING",
  "moonmoon loves the view count, he will, keep forcing rp with xqc every single day, 40 year old guy got lucky and is milking it out the wazoo so he doesnt have to go back to his mom’s attic.",
  "I CANT WITH THIS GUY ,#ez15% #powergaming #CoPixel #metagamer #allowed???",
  "how is this a real comment",
  "moonmoons chat is quite lit,erally the most hiveminded on Twitch that regurgitates everything he says.",
  "i think a few yung dab streams could get his groove back but his new material aint working for no body,.",
  "you’d expect him of all people to uphold nopixels standards but so far hes been treating 3.0 like his pe,rsonal circus and doesnt respect any ones rp accept his own, which is, to put it lightly, not what it used to be.",
  "is any one else shocked to see moonmoon behaving like this?",
  "Fuck you pussy bitch,such a jealous and ha,tefull person holy shit. What need is there to ruin someone’s experience with a game and hurt their career like wtf?",
  "hi (XQC viewer here). why is this streamer not malding ? i dont understand ? if he lost RP then he should be raging and calling things fail rp but hes not. wha,ts wrong with this guy ? 󠀀?",
  "Oh man. Moonmoon is about to ruin some really good rp :/ cant ever have fun in the server bc of this loser",
  'omg dude i am tired of gta holy shit ,i am so sorry i’ve been holding this for awhile , i know it’s your stream and everything, but fuck gta man that fucking roblox guy saying "block trial" is killing me',
  "Bro I’m just as mad about x getting banned and penta being free to play the game even though he’s toxic as fuck but all we are doing is helping moon moons viewer count",
  'when cop do stupid shit to felix nothing is done, so felix hard mald and do dumb shit and THEN admin are like: "Ban felix" and it like this everytim if you look back at, all the time felix got ban. truly disappoint from all angels (admins, cops, felix)',
  'Cop be asshole and felix sometime be asshole, when cop do stupid shit to felix nothing is done, so felix hard mald and do dumb shit and THEN admin are like: "Ban felix" and it like this everytim if you look back at all the time felix got ban. truly dis,appoint from all angels (admins, cops, felix)',
  'I finally und,erstood it. Cop sometime be asshole and felix sometime be asshole, when cop do stupid shit to felix nothing is done, so felix hard mald and do dumb shit and THEN admin jump in and are like: "Ban felix" and it like this everytim if you look back at all the time felix got ban. truly disappoint from all angels (admins, cops, felix)',
  "my opinion is, X got too big for the server, some admins got jealous that he had 100k concurrent and wanted more traction there way",
  "Uh oh now X isn’t paying 75% of the police Rp’rs income :’( I’m talkin in game AND irl lol",
  "Moon Mon is such a baby, literally malds and is being a prick to everyone on the server. St,ill he ends up going free. Its probably for the better, that x is banned. This NoPixel server is just too trashy atm.",
  'i feel like n,o pixel don’t rlly care for its "citizen RP players" only just buffing its police department lol idk just me',
  'when cop do stupid shit t,o felix nothing is done, so felix hard mald and do dumb shit and THEN admin are like: "Ban felix" and it like this everytim if you look back at all the time felix got ban. truly disappoint from all angels (admins, cops, felix)',
  "All ive learned from watching RP, is about half the time its fun, and half the time you’re getting griefed by the cops.",
  "A wise man once said, “A smart person learns from their mistakes, but a smarter person learns from other people’s mistak,es.” Hopefully the members on NoPixel will take that advice. #LetEmKnow",
  "I really want to see what it’ll be like in the coming weeks/month without X, because it was fun as hell to watch him be full pepega during car chases and mald. I wouldn’t be surprised if strea,mers leave the server from being bored of metagaming cops",
  'i feel like no pixel don’t rlly care for its "citizen RP players" only just buffing its police department lol idk just me',
  "Moon Mon is such a baby, literally malds and is being a prick to everyone on the server. Still he ends up going free. Its ,probably for the better, that x is banned. This NoPixel server is just too trashy atm.",
  "xQc could potentially make his own server and have it ran fairly,inviting other popular streamers to play in it along with people who are very good proven role players.",
  "xqc says the truth: gets banned damn I feel like we back in 60-80s censor ship times boys",
  "When I first saw the Nopixel 3.0 trailer, I wanted to try it out it looked soo dope. But w,atching moon play and seeing how the community behaves and how tough it even is to enter changed my mind.",
  "As X once said “Ride like thunder, crash like lightning.” Wonder what lenny will do without the only good crim",
  "RIP Jean Paul (we know he will be back) #LetEmKnow",
  "The only reason people know of nopixel is because o,f X they kept unbanning him because he brought the server more attention. He doesn’t need nopixel, they need him.",
  "Police gonna get even Maldier when they gonna realise the only reason they were having fun it’s because of crims like X",
  "People can’t handle his juice so they metagame and failRP just to arrest him, he still gets payed the end of the day, he, playing a character and they don’t really realise that they giving x publicity, money and views. X got the W in the end",
  "Moonmoon is the biggest power gamer in the server and he loves being called that, its crazy how he hasn’t gotten banned yet",
  "This man could litterally go ok a killing spree for no reason on his cop character and th,e admins won’t do sh*t I garauntee.",
  "Moon is a loser, I’m sorry you guys can’t see that.",
  "Listening to them OOC go off about X calling him a p,rick etc. is funny af. The fact these old men can’t compose themselves over a guy in his 20s really shows their true characters. 😂 🤣",
  "moonmoon the type of guy to pour his milk BEFOR cereal omegalul what a poewrgamer",
  "your average cop mentality, desync = cheating, grabbing people thru walls = rolepl,ay (lol)",
  "This The Stream Of The W Hungry Cop That Keeps Rui,ning All The RP???? OMEGALUL",
  'I just watched moonmoon "accidentally" kill people, How is he Cop still???',
  "These Cops Need To Chill FR! What Is Moon Moon Even Doing Anymore???",
  "Damn moon, he, was one of my face cop on the server. Ever since yesterday stream, he changed. peeposad!",
  "good job pent,a & moonmoon, hope you guys are happy now",
  "Moon moon only knows how to play toxic over the top cha,racters that end up being forced to perma/lose their job. Look back at 2.0 and conveniently wrangler did too. They are bad rp’ers. They can’t do anything in moderation",
  "Moon moon only knows how to play toxic over the top characters that end up being forced to perma/lose their job. Look back at 2.0 and conveniently wrangler did too. They are bad rp’ers. They can’t do anything in moderation",
  "Moon always contradicts himself lmao he just needs to stop trying to act morally superior because he’s too dumb to keep it up.",
  "Damn moon, he was one of my face cop on the server. Ever since yesterday x was banned, he changed. Sadge",
  "How MoonMoon has viewers is beyond me.",
  "This man could litterally go ok a killi,ng spree for no reason on his cop character and the admins won’t do sh*t I garauntee.",
  "Damn moon, he was one of my face cop on the server. Ever since yesterday stream, he changed. peepocry",
  "WHO tf is a moon moon? No fame n,o hair no friends",
  "XQC lives in 40year old mans greased up, boomers head rent free",
  "I don’t understand how PENTA’s character and MOONMOON’s charact,er can get away with the stuff they get away with without getting like a 3 day ban",
  "This stream is negative one bazillion cringe. Moon can’t act, can’t RP, can’t do anything interesting.",
  "Just gonna say Yung Dab > Lenny Hawk imo",
  "This guy is the most tryhard person I hav,e ever seen on a Content Rolepay Server. Sad",
  "Cops on NoPixel are literal power hungry children, If I ran that butt stick of a serve,r I’d make A LOT of changes",
  "Moonmoon is the biggest power gamer in the server and he loves being called that, its crazy how he hasn’t gotten b,anned yet",
  "I heard a new drug came out for cops yesterday think it’s called OOC mald",
  "Moonmoon definitely peaked at OW ever since then, hes just straight up unb,earable",
  "I fucking love MoonMoon but his community is as toxic as the juicers these days, sad to s,ee.",
  "This dude always insulting people viewers 🤔 He had the best Community right? 😂",
  "I fucking love MoonMoon but his community is as toxic as the juicers these days, ,sad to see.",
  "Moon sound like British colonial who make democracy right after killing millions of people",
  "Please play the block or something today.",
  "I CANT WITH THIS GUY #ez15% #powergaming #,CoPixel #metagamer #allowed???",
  "#LetEmKnow",
  "rent free b,tw",
  "a man child oo,c malding every time he takes a L is definitely fun for everyone.",
  "How TF does 18k ppl sub to this guy and watch him 🤦♂️.. Actual dogshit",
  "this guy wouldnt be cringe if he didnt try to play shit off, its a video, game who cares if you get a little power gamey but dont act like you didnt do what you just did, guy has the moral composition of a snake",
  "🤣😭FRICKIN COP WATCHERS😭😂💀HERE YOU NEED THIS W?!?!?!? i know know you can’t take L’s",
  "Moon is trash, he always powergames and uses a personal vendetta ooc.",
  "Wtf? These cops are ridiculous power gaming.",
  "Damn mr.METAMOON AND POWERMOON SHEEEEEEEEEEEE,EEEEEEeSH",
  "this dude is too cringe and needs a time out ban",
  "I wish the crims will unite and clap the PD. Like, metagaming and power gaming cops needs to get the biggest L ever.",
  "40yr old Malder YIKES",
  "#METAMOON",
  "Moon moon ,= EGO Gaming. Breaking the RP of nopixel....",
  "Moonmoon is clearly pushing the trolling until he’s ban,ned.... he doesn’t give a fuck about rp in general and others players...",
  "Powergaming. Not cool.",
  "Moon has been so cringe, in rp lately.",
  "man moonmoon has a cult like following, its so weirdchamp",
  "rent free btw",
  "#LetEmKnow #Le,tEmKnow #LetEmKnow #LetEmKnow #LetEmKnow #LetEmKnow #LetEmKnow #LetEmKnow #LetEmKnow",
  "u r a biiiig loooserrr cop",
  "kids forget its a video gam,e moonmoon thinks he is a real cop he takes this game too seriously",
  "moonmoon loves the view count, he will keep forcing rp with xqc every single day, 40 year old g,uy got lucky and is milking it out the wazoo so he doesnt have to go back to his mom’s attic.",
  "moonmoons chat is quite literally the most hiveminded on Twitch that regurgitates everything he says.",
  "ooc mald",
  "I fucking, love MoonMoon but his community is as toxic as the juicers these days, sad to see.",
  "Moon sound like British colonial who make democracy right after killing millions of people",
  "Please play the block or something today.",
  "I CANT WITH THIS GUY #ez15% #powergaming #,CoPixel #metagamer #allowed???",
  "#LetEmKnow",
  "rent free b,tw",
  "a man child oo,c malding every time he takes a L is definitely fun for everyone.",
  "How TF does 18k ppl sub to this guy and watch him 🤦♂️.. Actual dogshit",
  "this guy wouldnt be cringe if he didnt try to play shit off, its a video, game who cares if you get a little power gamey but dont act like you didnt do what you just did, guy has the moral composition of a snake",
  "🤣😭FRICKIN COP WATCHERS😭😂💀HERE YOU NEED THIS W?!?!?!? i know know you can’t take L’s",
  "Moon is trash, he always powergames and uses a personal vendetta ooc.",
  "Wtf? These cops are ridiculous power gaming.",
  "Damn mr.METAMOON AND POWERMOON SHEEEEEEEEEEEE,EEEEEEeSH",
  "this dude is too cringe and needs a time out ban",
  "I wish the crims will unite and clap the PD. Like, metagaming and power gaming cops needs to get the biggest L ever.",
  "40yr old Malder YIKES",
  "#METAMOON",
  "Moon moon ,= EGO Gaming. Breaking the RP of nopixel....",
  "Moonmoon is clearly pushing the trolling until he’s ban,ned.... he doesn’t give a fuck about rp in general and others players...",
  "Powergaming. Not cool.",
  "Moon has been so cringe, in rp lately.",
  "man moonmoon has a cult like following, its so weirdchamp",
  "rent free btw",
  "#LetEmKnow #Le,tEmKnow #LetEmKnow #LetEmKnow #LetEmKnow #LetEmKnow #LetEmKnow #LetEmKnow #LetEmKnow",
  "u r a biiiig loooserrr cop",
  "kids forget its a video gam,e moonmoon thinks he is a real cop he takes this game too seriously",
  "moonmoon loves the view count, he will keep forcing rp with xqc every single day, 40 year old g,uy got lucky and is milking it out the wazoo so he doesnt have to go back to his mom’s attic.",
  "moonmoons chat is quite literally the most hiveminded on Twitch that regurgitates everything he says.",
  "ooc mald",
  "someone n,eeds to make a better version of nopixel, not nopixel 4.0 but a whole new server with new admins etc",
  "rent free btw",
  "if any other j,uicers see this, STOP WATCHING THE STREAM!! we are only giving this powergaming cheater MORE attention! :O :O :O",
  "STOP BEING COP!!!",
  "if any other juice,rs see this, STOP WATCHING THE STREAM!! we are only giving this powergaming cheater MORE attention!",
  "is he powergaming agane?",
  "#LetEmKnow",
  "u coops can, suk my big but",
  "frick lenny",
  'I just watch,ed moonmoon "accidentally" kill people, How is he Cop still???',
  "@moonmoon so uh. we’re just gonna sit around for 3 hours? when’s the next c,ar chase or heist bust? or even just rob block this is boring.",
  "reminds me of someone",
  "so you guys just cop s,tack for fun now huh?",
  "lenny is the downfall of nopixel",
  "lenny doesnt deserve swat imo",
  "imagine powergaming",
  "40yr old Malder YIKE,S",
  "#METAMOON",
  "Moon moon ,= EGO Gaming. Breaking the RP of nopixel....",
  "Moonmoon is clearly pushing the trolling until he’s ban,ned.... he doesn’t give a fuck about rp in general and others players...",
  "Powergaming. Not cool.",
  "Moon has been so cringe, in rp lately.",
  "man moonmoon has a cult like following, its so weirdchamp",
  "rent free btw",
  "#LetEmKnow #Le,tEmKnow #LetEmKnow #LetEmKnow #LetEmKnow #LetEmKnow #LetEmKnow #LetEmKnow #LetEmKnow",
  "u r a biiiig loooserrr cop",
  "kids forget its a video gam,e moonmoon thinks he is a real cop he takes this game too seriously",
  "moonmoon loves the view count, he will keep forcing rp with xqc every single day, 40 year old g,uy got lucky and is milking it out the wazoo so he doesnt have to go back to his mom’s attic.",
  "moonmoons chat is quite literally the most hiveminded on Twitch that regurgitates everything he says.",
];
